package skywolf46.extrautility.core.test.exceptions

class TestException : RuntimeException()